call plug#begin('~/.vim/plugged')
    " NERD
    Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
    Plug 'scrooloose/nerdcommenter'
    Plug 'low-ghost/nerdtree-fugitive'

    " JavaScript
    Plug 'pangloss/vim-javascript'
    Plug 'mxw/vim-jsx'
    Plug 'moll/vim-node'
    Plug 'posva/vim-vue'

    "Typescript
    Plug 'leafgarland/typescript-vim'
    Plug 'Quramy/vim-js-pretty-template'
    Plug 'jason0x43/vim-js-indent'

    " Colorscheme
    Plug 'altercation/vim-colors-solarized'

    Plug 'tpope/vim-fugitive'
    Plug 'ctrlpvim/ctrlp.vim'
    Plug 'dkprice/vim-easygrep'
    Plug 'itchyny/lightline.vim'
    Plug 'mfukar/robotframework-vim'
    Plug 'junegunn/vim-easy-align'

    "Surround
    Plug 'tpope/vim-unimpaired'
    Plug 'tpope/vim-surround'
    Plug 'tpope/vim-repeat'

    "Snippets
    Plug 'MarcWeber/vim-addon-mw-utils'
    Plug 'tomtom/tlib_vim'
    Plug 'garbas/vim-snipmate'
call plug#end()

" Recommended settings
set nocompatible
filetype off

" Syntax and plugin settings
filetype plugin indent on
syntax enable

set nowrap
set list
set relativenumber
set laststatus=2

set clipboard^=unnamed,unnamedplus

" Light line
let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ }

" List characters
set listchars=tab:>\ ,trail:.,extends:#,nbsp:.

" Enable mouse
set mouse=a

" Set temp directory
set backupdir=$HOME/.vimswap
set directory=$HOME/.vimswap

" Default indention settings
set noet
set ts=4
set sw=4
set sts=4

" Encoding settings
set encoding=utf-8

" Backspace settings: work like most apps in insert mode
set backspace=indent,eol,start

" Color settings
let solarized_dir="$HOME/.vim/plugged/vim-colors-solarized"

if has('windows') && !has('unix') && !has('gui_running')
    set bg=dark
    colo default
elseif isdirectory(expand(solarized_dir))
    " Color scheme
    set t_Co=256
    set bg=light
    let g:solarized_termcolors=256
    let g:solarized_termtrans=1
    let g:solarized_contrast='normal'
    let g:solarized_visibility='normal'
    colo solarized
else
    colo solarized
endif

" If gvim
if has('gui_running')
    " Remove toolbars
    set guioptions-=T  "remove toolbar
    set guioptions-=m  "remove menu bar
    set guioptions-=r  "remove right-hand scroll bar
    set guioptions-=L  "remove left-hand scroll bar

    " Set gui font
    if has('unix')
        set guifont=DejaVu\ Sans\ Mono\ 9
        set guifontwide=DejaVu\ Sans\ Mono\ 9
    else
        set guifont=Consolas:h9
    endif
endif

function! StripTrailingWhitespace()
    " Preparation: save last search, and cursor position.
    let _s=@/
    let l = line('.')
    let c = col('.')
    " do the business:
    %s/\s\+$//e
    " clean up: restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction

" cd to dir if opening a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | ene | exe 'cd' argv()[0] | echo '' | endif

" Ctrlp ignore
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|(node_modules))$',
  \ 'file': '\v\.(exe|so|dll|zip|gz|rar)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }

let g:ctrlp_user_command = [
  \ '.git/',
  \ 'git --git-dir=%s/.git ls-files -oc --exclude-standard'
  \ ]

"
" Default find settings
"
set wildignore+=node_modules/**
set path+=src/**
set path+=lib/**
set wildmenu

" Commenter
let g:NERDSpaceDelims = 1

" Whiplash
let g:WhiplashProjectsDir = "$HOME/projects"
let g:WhiplashCommandName = "Project"

"
" KEYBINDINGS
"

" Map leader to unused key in normal mode
let mapleader=" "

" Tab navigation
nnoremap <leader>l                  :tabn<cr>
nnoremap <leader>h                  :tabp<cr>
" Tabonly
nnoremap <leader>to                 :tabo<cr>

" NERDTree
nnoremap <leader>e                  :NERDTreeToggle<cr>
nnoremap <leader>qq                 :qa!<cr>

" Session management

" Add/Save session
nnoremap <leader>sa                 :mksession $HOME/.vim/sessions/
nnoremap <leader>ss                 :mksession! $HOME/.vim/sessions/

" Load session
nnoremap <leader>sl                 :source $HOME/.vim/sessions/

" fugitive key bindings
nnoremap <leader>gs                 :Gstatus<cr>
nnoremap <leader>gc                 :Gcommit<cr>
nnoremap <leader>gpl                :Gpull<cr>
nnoremap <leader>gps                :Gpush<cr>

" Buffer delete
nnoremap <leader>d                  :bd<cr>

" Easy align
nmap ga                             <Plug>(EasyAlign)
xmap ga                             <Plug>(EasyAlign)

