call plug#begin('~/.vim/plugged')
  Plug 'tpope/vim-sensible'
  Plug 'tpope/vim-fugitive'
  Plug 'itchyny/lightline.vim'
  Plug 'mfukar/robotframework-vim'
  Plug 'junegunn/vim-easy-align'
  Plug 'junegunn/fzf.vim'
  Plug 'joereynolds/SQHell.vim'
  Plug 'tpope/vim-abolish'
  Plug 'airblade/vim-gitgutter'
  Plug 'Shougo/unite.vim'
  Plug 'Shougo/vimproc.vim', {'do' : 'make'}
  Plug 'tmux-plugins/vim-tmux'
  Plug 'tpope/vim-dispatch'

  " Vim scripts
  Plug 'vim-scripts/SQLUtilities'
  Plug 'vim-scripts/Align'

  " NERD
  Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
  Plug 'scrooloose/nerdcommenter'
  Plug 'low-ghost/nerdtree-fugitive'

  " JavaScript
  Plug 'pangloss/vim-javascript'
  Plug 'mxw/vim-jsx'
  Plug 'moll/vim-node'
  Plug 'posva/vim-vue'
  Plug 'idanarye/vim-vebugger', { 'branch': 'develop' }

  " Typescript
  Plug 'leafgarland/typescript-vim'
  Plug 'Quramy/vim-js-pretty-template'
  Plug 'jason0x43/vim-js-indent'
  Plug 'mhartington/vim-typings'
  Plug 'Quramy/tsuquyomi'

  " Colorscheme
  Plug 'altercation/vim-colors-solarized'

  "Surround
  Plug 'tpope/vim-unimpaired'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-repeat'

  "Snippets
  Plug 'MarcWeber/vim-addon-mw-utils' " Required by snipmate
  Plug 'tomtom/tlib_vim' " Required by snipmate
  Plug 'garbas/vim-snipmate'

  "Prettier
  Plug 'prettier/vim-prettier', { 'do': 'yarn install' }

  "Syntax checker
  Plug 'w0rp/ale'

  " Typescript
  Plug 'leafgarland/typescript-vim'
  Plug 'Quramy/vim-js-pretty-template'

  if has('nvim')
    " Neovim colors
    Plug 'iCyMind/NeoSolarized'
  endif

  " Wakatime
  Plug 'wakatime/vim-wakatime'

  " Conquer of Completion
  Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
call plug#end()

