# Oh My Zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="simple"
plugins=(git)

# User configuration
PATH="$HOME/.composer/vendor/bin:$HOME/opt/node/bin:$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
PATH="$PATH:$HOME/.deno/bin"
export PATH

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Java
export JAVA_HOME="$HOME/opt/java/bin/java"
export PATH="$HOME/opt/java/bin:$PATH"

SCM=$HOME/scm
export DOTFILES=$SCM/identor/dotfiles
export ENV=$HOME/.env
export KUBECONFIG=$HOME/.config/kube

# Aliases
# Config: cfg
alias cfgzsh="vim $DOTFILES/zsh/zshrc && $DOTFILES/zsh/install.sh && source $HOME/.zshrc"
alias cfgvim="vim $DOTFILES/vim/vimrc && $DOTFILES/vim/install.sh"
alias cfgswrx="vim $SCM/mclinica/swiperx/cli/app/config.js"
alias cfgx11="vim $DOTFILES/x11/xresources && $DOTFILES/x11/install.sh && xrdb -merge ~/.Xresources"
alias cpd='echo -en `pwd`/ | xclip -selection clipboard'

# Git alias
alias Gstatus="git status"
alias Gpull="git pull"
alias Gpush="git push"
alias Gcommit="git commit"

## Current projects: cproj
export DWEB=$SCM/danisonbuilders/www
export SWRX=$SCM/mclinica/swiperx
export EULR=$SCM/identor/project-euler
export JS30=$SCM/identor-javascript30

export SWRX_ENV=$SWRX/env/swrx

function cproj() {
    $1; cd $1; tmux -2 new -s $1 || tmux -2 a -t $1
}

# run projects
alias cprojdweb="cproj $DWEB"
alias cprojswrx="cproj $SWRX"
alias cprojeulr="cproj $EULR"
alias cprojjs30="cproj $JS30"

# k8s
alias k="kubectl"

# fzf vim
alias vimf='vim `fzf`'

# Dotenv
alias de="dotenv -e"

# Xclip
alias xclipc="xclip -sel clip"

# Supported variables
# $DB_DEFAULT - default database
# $DB_PASSWORD - password
# $DB_HOST - hostname
# $DB_USER - username
function mysqlenv () {
    env=$1
    shift

    # Don't expose variables exported via `export` call
    (
        export $(cat $env | xargs) &&
        mysql -u$DB_USER -p$DB_PASSWORD -h$DB_HOST $DB_DEFAULT $@
    )
}

# Mysql
alias mysqlswrxcore="mysqlenv $ENV/swrx/core/production"
alias mysqlswrxcorestg="mysqlenv $ENV/swrx/core/staging "
alias mysqlswrxmodule="mysqlenv $ENV/swrx/module/production "
alias mysqlswrxmodulestg="mysqlenv $ENV/swrx/module/staging "

# SwipeRx CLI
alias swiperxstg="de $SWRX_ENV/cli/staging swiperx"
alias swiperxlocal="de $SWRX_ENV/cli/local swiperx"

alias notes="vim +cd $SCM/identor/notes"

# Use python 3
alias python=python3
alias pip=pip3

# Date now Reverse timestamp
alias datenow="date +%Y%m%d%H%M"

# bypass zsh glob pattern
unsetopt nomatch

source ~/.profile

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### Add ~/bin to PATH
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# fzf - enable fuzzy file search bindings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source environment variables
[ -f ~/.env/secret ] && source ~/.env/secret

# Merge ~/.Xresources
xrdb -merge ~/.Xresources

