# Oh My Zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="simple"
plugins=(git)

# Source environment variables
[ -f ~/.env/secret ] && source ~/.env/secret

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Supported variables
# $DB_DEFAULT - default database
# $DB_PASSWORD - password
# $DB_HOST - hostname
# $DB_USER - username
function dbenv () {
    env=$1
    shift

    prog=$1
    shift

    # Don't expose variables exported via `export` call
    (
        export $(cat $env | xargs) &&
        $prog -u$DB_USER -p$DB_PASSWORD -h$DB_HOST $DB_DEFAULT $@
    )
}

function mysqlenv () {
    env=$1
    shift

    dbenv $env mysql $@
}

function mysqldumpenv () {
    env=$1
    shift

    dbenv $env mysqldump $@
}

function cproj() {
    $1; cd $1; tmux -2 new -s $1 || tmux -2 a -t $1
}

# Aliases
# Git alias
alias Gstatus="git status"
alias Gpull="git pull"
alias Gpush="git push"
alias Gcommit="git commit"

# k8s
alias k="kubectl"

# fzf vim
alias vimf='vim `fzf`'

# Dotenv
alias de="dotenv -e"

# Xclip
alias xclipc="xclip -sel clip"

# Use python 3
alias python='/usr/bin/python3'
alias pip='/usr/bin/python3 -m pip'

# Date now Reverse timestamp
alias datenow="date +%Y%m%d%H%M"
alias today="date +%Y%m%d"

# bypass zsh glob pattern
unsetopt nomatch

[ -f ~/.profile ] && source ~/.profile

# fzf - enable fuzzy file search bindings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Merge ~/.Xresources
xrdb -merge ~/.Xresources

# User path configurations
PATH="$PATH:$HOME/.deno/bin"
export PATH

# Java
export JAVA_HOME="$HOME/opt/java/bin/java"
export PATH="$HOME/opt/java/bin:$PATH"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

